05_ManyToMany_CRUD/notices/urls.py
from django.urls import path
from . import views

# 동일한 url이름을 구분하기 위한 app_name 작성
app_name = 'notices'
urlpatterns = [
    # name : url의 이름 설정
    path('', views.index, name='index'), # 전체 게시글 조회 url
    path('create/', views.create, name='create'),# 게시글 생성 url
    # Variable Routing
    path('<int:pk>/', views.detail, name='detail'), # 개별 게시글 상세 페이지 url
    path('<int:pk>/delete/', views.delete, name='delete'), # 개별 게시글 삭제 url
    path('<int:pk>/update/', views.update, name='update'), # 개별 게시글 수정 url
    path('<int:pk>/comments/', views.comment_create, name='comment_create'), # 댓글 작성 url
    path('<int:notice_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'), # 댓글 삭제 url
    path('<int:notice_pk>/likes/', views.likes, name='likes'), # 좋아요 기능 url
]

05_ManyToMany_CRUD/notices/models.py
from django.db import models
from django.conf import settings

# Model 클래스를 상속 받음
class Notice(models.Model):
    # M:N 관계 설정
    # 역참조 이름 중복(User와 Notice)으로 related_name 추가
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_notices')
    # user와 Notice 1:N 외래키 설정
    # user 모델 참조는 함수(get_user_model())로 진행하지 않고, settings.AUTH_USER_MODEL(반환값은 문자열임)로 진행
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

class Comment(models.Model):
    # 외래키 설정
    # 참조하는 모델명_id로 데이터베이스 필드 명이 생성됨
    # 명시적 모델관계를 위해 클래스명을 소문자 단수형으로 작성하는 것이 바람직함
    # article과 Comments의 1:N 외래키 설정
    notice = models.ForeignKey(Notice, on_delete=models.CASCADE) # 마이그레이션하면 마지막에 생성됨
    # user와 Comments의 1:N 외래키 설정
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content =  models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

05_ManyToMany_CRUD/notices/forms.py
from django import forms
from .models import Notice, Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('notice', 'user',)

class NoticeForm(forms.ModelForm):
    # widgets을 활용한 input 요소 표현
    title = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'my-title form-control',
                'placeholder': '제목을 입력해주세요',
            }
        )
    )
    content = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'class': 'my-content form-control',
            }
        ),
        error_messages={
            'required': '내용을 입력해주세요',
        }
    )

    class Meta:
        # 어떤 모델을 기반으로 Form을 작성할 것인지 작성
        model = Notice 
        fields = ('title', 'content',)
        # exclude : 특정 필드를 제외할 때 사용, fields와 동시 사용 불가

05_ManyToMany_CRUD/notices/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Notice, Comment
from .forms import NoticeForm, CommentForm
# HTTP 기능을 지원하는 데코레이터
from django.views.decorators.http import require_http_methods, require_POST, require_safe
# 로그인한 사용자만 접근 가능하도록 제한하는 데코레이터
# 인증 성공 시, 사용자가 redirect 되어야하는 경로는 next라는 쿼리 문자열 매개변수에 저장됨
# 비로그인 상태에서 로그인 상태에만 접근 가능한 경로를 입력하여 url에서 next에 해당하는 변수 확인 가능
from django.contrib.auth.decorators import login_required


# Read : 전체 게시글 조회
@require_safe # GET만을 허용
def index(request):
    notices = Notice.objects.order_by('-pk')
    context = {
        'notices' : notices
    }
    return render(request, 'notices/index.html', context) # 전체 게시글 목록을 반환


# Create : 게시글 생성
# new와 create 함수가 method만 다를 뿐 같은 역할을 하고 있음
@login_required 
@require_http_methods(['GET', 'POST']) # 특정 메소드 요청만 허용
def create(request):
    # POST일 경우, create 역할
    if request.method == 'POST':
        # ModelForm을 이용하여 데이터를 받음
        form = NoticeForm(request.POST)
        # is_valid() : 데이터의 유효성 검사, boolean으로 결과를 반환
        if form.is_valid():
            # 작성자 정보를 포함시켜야 함
            notice = form.save(commit=False)
            notice.user = request.user
            notice.save() # DB에 저장    
            # 새 url로 요청 전송
            return redirect('notices:detail', notice.pk)
        
    # POST가 아닌 경우, new 역할 
    else:
        form = NoticeForm()
    # 유효성 검사를 통과하지 못한 경우
    context = {
        'form' : form,
    }
    return render(request, 'notices/create.html', context)

# Read : 개별 게시글 조회, 댓글 조회
@require_safe # GET만을 허용
def detail(request, pk):
    # get()을 호출하며, 상황에 따라 적절한 예외처리 진행
    notice = get_object_or_404(Notice, pk=pk)
    # CommentForm을 이용한 댓글 출력
    comment_form = CommentForm()
    # 조회한 notice의 모든 댓글을 조회 : 역참조
    comments = notice.comment_set.all()
    context = {
        'notice' : notice,
        'comment_form' : comment_form,
        'comments' : comments,
    }
    return render(request, 'notices/detail.html', context)

# Delete : 게시글 삭제
# 데코레이터의 충돌 발생 : 로그인 검증 후, next 경로로 redirect 될 때 GET으로 처리되어
# POST 데이터를 잃어버리고, @require_POST와 충돌발생 
# login_required를 내부에서 처리  
@require_POST # POST만을 허용 : 조건문을 통해 POST 이외의 메소드 요청을 처리할 이유가 사라짐
def delete(request, pk):
    notice = get_object_or_404(Notice, pk=pk)
    if request.user.is_authenticated:
        # 삭제를 요청한 유저와 작성한 유저가 같아야 삭제 가능
        if request.user == notice.user:
            notice.delete()
            return redirect('notices:index')
    return redirect('notices:detail', notice.pk)



# Update : 게시글 수정
# edit과 update 함수가 method만 다를 뿐 같은 역할을 하고 있음
@login_required 
@require_http_methods(['GET', 'POST']) # 특정 메소드 요청만 허용
def update(request, pk):
    notice = get_object_or_404(Notice, pk=pk)
    # 자신이 작성한 글만 수정
    if request.user == notice.user:
        # POST일 경우, update 역할
        if request.method == 'POST':
            # ModelForm을 이용하여 데이터를 받음
            form = NoticeForm(request.POST, instance=notice)
            # is_valid() : 데이터의 유효성 검사, boolean으로 결과를 반환
            if form.is_valid():
                notice = form.save()
                return redirect('notices:detail', notice.pk)

        # POST가 아닌 경우, edit 역할 
        else:
            form = NoticeForm(instance=notice)
    # 본인이 작성한 글이 아닌 경우
    else:
        return redirect('notices:index')

    context = {
        'form' : form,
        'notice' : notice,
    }
    return render(request, 'notices/update.html', context)

# Create : 댓글 생성
@require_POST
def comment_create(request, pk):
    # 기존 detail 페이지에서 댓글 작성이 처리가 되고 있음
    # 따라서 POST에 대한 처리만 하면 됨
    # 만약 댓글 작성에 대한 단독 페이지가 있다면, GET이 필요
    # 인증된 사용자만 접근
    if request.user.is_authenticated:
        notice = get_object_or_404(Notice, pk=pk)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            # commit=False : 아직 데이터베이스에 저장되지 않은 인스턴스를 반환
            # 어떤 게시글에 작성하는지를 제외하였기 때문에
            # commit을 이용하여 DB에 저장은 안하지만 인스턴스만 리턴으로 제공하겠다는 의미로 작성해줌
            # 즉, 누락했던 글을 작성할 시간이 생김
            comment = comment_form.save(commit=False)
            # 누락했던 값을 몇번 게시글에 작성될 글인지 작성하고
            comment.notice = notice
            # 현재 댓글을 달려는 사용자를 외래키로 추가해야 댓글이 달림
            # user와 comments를 1:N 으로 관계를 설정하였기 때문
            comment.user = request.user
            # 저장
            comment.save()
        return redirect('notices:detail', notice.pk)
    # 사용자 인증에 실패한 경우
    return redirect('accounts:login')

# Delete : 댓글 생성
# 현재 없는 notice의 pk를 얻기 위한 방법 2 : variable routing
# def comment_delete(request, article_pk, comment_pk):
# 2번을 사용, 이유는 url 구조의 일관성 유지를 위해
@require_POST
def comment_delete(request, notice_pk, comment_pk):
    # 인증된 사용자만 접근
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, pk=comment_pk)
        # 현재 없는 notice의 pk를 얻기 위한 방법 1. notice = comment.notice.pk
        # 인증된 사용자 중 댓글 작성자와 같은 사람만 삭제 가능
        # 가리는 것보다 view에서 막는게 더 좋음, 보안 신경 쓰기
        if request.user == comment.user:
            comment.delete()
    return redirect('notices:detail', notice_pk)


@require_POST
def likes(request, notice_pk):
    if request.user.is_authenticated:
        notice = get_object_or_404(Notice, pk=notice_pk)
        # 이 게시글에 좋아요를 누른 유저 목록에 현재 요청하는 유저가 있다면
        # exists : 쿼리셋에 결과의 포함여부에 따라 boolean 형식으로 결과 반환
        if notice.like_users.filter(pk=request.user.pk).exists():
            # 좋아요 취소
            notice.like_users.remove(request.user)
        else:
            notice.like_users.add(request.user)
        return redirect('notices:index')
    return redirect('accounts:login')

05_ManyToMany_CRUD/notices/templates/notices/create.html
<!-- 템플릿 상속 -->
{% extends 'base.html' %}

<!-- Create : 게시글 생성 -->
{% block content %}
  <h1 class = "text-center"> Notice Create Page</h1>
  <hr>
  <!-- 입력 받은 데이터를 create로 전달 -->
  <form action="{% url 'notices:create' %}" method="POST">
    <!-- csrf 공격 방어 -->
    {% csrf_token %}
    <!-- form을 이용한 출력-->
    <!-- as_p : 각 필드가 <p>태그로 감싸져서 렌더링 됨-->
    {{ form.as_p }}
    <input type="submit">
  </form>
  <hr>
  <!-- Read : 전체 게시글 조회 페이지 이동 버튼 -->
  <a href="{% url 'notices:index' %}">[back]</a>
{% endblock content %}

05_ManyToMany_CRUD/notices/templates/notices/detail.html
<!-- 템플릿 상속-->
{% extends 'base.html' %}

<!-- Read : 개별 게시글 조회 -->
{% block content %}
  <h1>Notice Detail Page</h1><hr>
  <h3>{{ notice.pk }}번째 글</h3>
  <hr>
  <p>제목 : {{ notice.title }}</p>
  <p>내용 : {{ notice.content }}</p>
  <p>작성 시각 : {{ notice.created_at }}</p>
  <p>수정 시각 : {{ notice.updated_at }}</p>
  <hr>
  <!-- 작성자만 수정 및 삭제--> 
  {% if user == notice.user %}
    <!-- Update : 게시글 수정 페이지 이동 버튼 -->
    <a href="{% url 'notices:update' notice.pk %}" class="btn btn-primary">[Edit]</a>

    <!-- Delete : 삭제 버튼 -->
    <!-- 입력 받은 데이터를 delete로 전달 -->
    <form action="{% url 'notices:delete' notice.pk %}" method="POST">
      <!-- csrf 공격 방어 -->
      {% csrf_token %}
      <button class="btn btn-danger">[Delete]</button>
    </form>
  {% endif %}


  <!-- Read : 전체 게시글 조회 페이지 이동 버튼 -->
  <a href="{% url 'notices:index' %}">[back]</a><hr>

  <!-- 댓글 개수 출력-->
  {% if comments %}
    <p><b>{{ comments|length }}개의 댓글이 있습니다.</b></p>
  {% endif %}
  <!-- 댓글 목록 출력-->
  <ul>
    {% for comment in  comments %}
      <li>
        <!--댓글 작성자 포함 출력-->
        {{ comment.user}} - {{ comment.content }}
        <!--삭제 요청 유저와 댓글 작성자가 같아야만 삭제버튼을 보여줘-->
        {% if  request.user == comment.user%}
          <form action="{% url 'notices:comment_delete' notice.pk comment.pk %}" method = "POST">
            {% csrf_token %}
            <input type="submit" value = "삭제">
          </form>
        {% endif %}
      </li>
    <!-- 댓글이 없는 경우 -->
    {% empty %}
    <p><b>댓글 없음</b></p>
    {% endfor %}
  </ul>

  {% if  request.user.is_authenticated %}
    <!--댓글 입력 부분 : 로그인한 사용자만 접근 가능함-->
    <form action="{% url 'notices:comment_create' notice.pk %}" method="POST">
      {% csrf_token %}
      {{ comment_form }}
      <input type="submit">
    </form>
  {% else %}
    <a href="{% url 'accounts:login' %}">[댓글작성하려면 로그인하세요]</a>
  {% endif %}
{% endblock content %}

05_ManyToMany_CRUD/notices/templates/notices/index.html
<!-- 템플릿 상속-->
{% extends 'base.html' %}

{% block content %}
  <h1 class = "text-center">Notice Index Page</h1>
  <hr>
  <!--로그인한 사용자만 글 작성이 가능해야 함-->
  {% if request.user.is_authenticated %}
    <!-- Create : 게시글 생성 버튼-->
    <a href="{% url 'notices:create' %}">Create</a>
  <!--로그인 하지 않은 사용자는 로그인을 하고 와야 함-->
  {% else %}
    <a href="{% url 'accounts:login' %}">[새 글 작성을 위해서는 로그인을 하고 와야 합니다.]</a>
  {% endif %}
  <hr>
  <!-- Read : 전체 게시글 조회 -->  
  {% for notice in  notices %}
    <p>작성자:  <a href="{% url 'accounts:profile' notice.user.username %}">{{ notice.user }}</a></p>
    <p>번호 : {{ notice.pk }}</p>
    <p>제목 : {{ notice.title }}</p>
    <p>내용 : {{ notice.content }}</p>
    <p>좋아요 수 : {{ notice.like_users.count }} </p>
    <!-- 좋아요 출력 -->
    <div>
      <form action="{% url 'notices:likes' notice.pk %}" method="POST">  
        {% csrf_token %}
        <!-- 좋아요를 선택한 경우-->
        {% if user in notice.like_users.all %}
          <button class="btn"><i class="fas fa-heart" style="color:crimson;"></i></button>
        <!-- 좋아요를 선택하지 않은 경우-->
          {% else %}
          <button class="btn"><i class="fas fa-heart" style="color:black;"></i></button>
        {% endif %}
      </form>
    </div>

    <!-- Read : 개별 게시글 조회 버튼-->
    <a href="{% url 'notices:detail' notice.pk %}">[detail]</a>
    <hr>
  {% endfor %}
{% endblock content %}

05_ManyToMany_CRUD/notices/templates/notices/update.html
<!-- 템플릿 상속-->
{% extends 'base.html' %}

<!-- Read : 개별 게시글 조회 -->
{% block content %}
  <h1 class="text-center">Notice Update Page</h1><hr>
  <!-- 수정한 데이터를 update으로 전달 -->
  <form action="{% url 'notices:update' notice.pk %}" method="POST">
    {% csrf_token %}
    <label for="title">제목: </label>
    <input type="text" name="title" value="{{ notice.title }}"><br>
    <label for="content">내용: </label>
    <textarea name="content" cols="30" rows="10">{{ notice.content }}</textarea>
    <input type="submit">
  </form>
  <!-- Read : 전체 게시글 조회 페이지 이동 버튼 -->
  <a href="{% url 'notices:index' %}">[back]</a>
{% endblock content %}