05_ManyToMany_CRUD/accounts/urls.py
from django.urls import path
from . import views

# 동일한 url이름을 구분하기 위한 app_name 작성
app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name = 'login'), # 로그인 url
    path('logout/', views.logout, name = 'logout'), # 로그아웃 url
    path('signup/', views.singup, name = 'signup'), # 회원가입 url
    path('delete/', views.delete, name = 'delete'), # 회원탈퇴 url
    path('update/', views.update, name = 'update'), # 회원정보 수정 url
    # password/는 기존 url과 맞춰준 것
    path('password/', views.change_password, name = 'change_password'), # 비밀번호 수정 url
    path('<username>/', views.profile, name='profile'), # 사용자 프로필 url
    path('<int:user_pk>/follow/', views.follow, name='follow'), # Follow url
]

05_ManyToMany_CRUD/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # app url mapping : 각 앱들의 url을 포함시킴
    path('notices/', include('notices.urls')),
    path('accounts/', include('accounts.urls')),
]

05_ManyToMany_CRUD/templates/base.html
<!-- 템플릿 상속 -->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <!--font awesome 로고 적용-->
  <script src="https://kit.fontawesome.com/1ad42b9825.js" crossorigin="anonymous"></script>
  <title>Document</title>
</head>
<body>
  <div class="container">

    <!--사용자 정보 출력-->
    <!--템플릿이 렌더링 될 때, 자동으로 호출 가능한 컨텍스트 데이터 목록 context processors에서  
        현재 사용자를 나타내는 auth.User 인스턴스는 템플릿 변수 {{ user }}에 저장됨-->
    <h3>현재 로그인된 사용자는 {{ user }} 입니다 .</h3>
    
    <!--로그인 여부에 따라 접근할 수 있는 부분이 달라져야 함-->
    <!--is_authenticated : User model의 속성 중 하나로 익명의 사용자 이외의 모든 User 인스턴스에 대해 항상 True
        인증 여부를 알 수 있지만, 권한과 관련이 없고 활성화 상태나 세션이 유효한지에 대해서는 확인하지 않음-->
      {% if request.user.is_authenticated %}
      <!--로그인 상태의 출력 = 인증된 사용자일 경우-->
        <!-- 프로필 버튼 생성 부분-->
        <a href="{% url 'accounts:profile' request.user.username %}">내 프로필</a>
        <!--회원정보 수정 링크 출력 부분-->
        <a href="{% url 'accounts:update' %}"> 회원정보 수정 </a><br>

        <!--로그 아웃 링크 출력 부분-->  
        <form action="{% url 'accounts:logout' %}" method="POST">
          {% csrf_token %}
          <input type="submit" value="logout">
        </form>
        
        <!--회원 탈퇴 링크 출력 부분-->
        <form action="{% url 'accounts:delete' %}" method = "POST">
          {% csrf_token %}
          <input type="submit" value="회원탈퇴">
        </form>
      
      {% else %}
       <!--로그인이 아닌 상태의 출력 = 인증된 사용자가 아닐 경우-->
        <!--로그인 링크 출력-->
        <a href="{% url 'accounts:login' %}"> Login </a><br>
        <!--회원가입 링크 출력 -->
        <a href="{% url 'accounts:signup'%}">signup</a>

      {% endif %}

    {% block content %}
    <!-- 하위 템플릿 재지정 블록 영역-->
    {% endblock content %}
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>